#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color \#2d2d2d
bspc config active_border_color \#777777
bspc config focused_border_color \#f0f0f0
bspc config presel_feedback_color \#777777

~/.fehbg
polybar default &
